# Generated by Django 6.0.4 on 2026-04-30 13:27

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', usuarios.models.UsuarioManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rol', 'SOCIO'), _negated=True), models.Q(('is_staff', False), ('is_superuser', False)), _connector='OR'), name='usuario_socio_sin_privilegios_admin'),
        ),
    ]
