# Generated by Django 6.0.4 on 2026-05-09 17:18

from django.db import migrations, models


def asignar_rol_superadministrador(apps, schema_editor):
    """Migra superusuarios existentes al rol reservado antes de crear restricciones."""
    Usuario = apps.get_model('usuarios', 'Usuario')
    Usuario.objects.filter(is_superuser=True).update(rol='SUPERADMINISTRADOR')


def restaurar_rol_administrador(apps, schema_editor):
    """Revierte el rol reservado al valor usado antes de esta migracion."""
    Usuario = apps.get_model('usuarios', 'Usuario')
    Usuario.objects.filter(is_superuser=True, rol='SUPERADMINISTRADOR').update(
        rol='ADMINISTRADOR'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0002_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('ENCARGADO_REGISTRO', 'Encargado de registro'), ('SUPERADMINISTRADOR', 'Superadministrador Django'), ('SOCIO', 'Socio')], default='SOCIO', max_length=20),
        ),
        migrations.RunPython(
            asignar_rol_superadministrador,
            restaurar_rol_administrador,
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(('is_superuser', False), ('rol', 'SUPERADMINISTRADOR'), _connector='OR'), name='usuario_superuser_rol_superadmin'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rol', 'SUPERADMINISTRADOR'), _negated=True), ('is_superuser', True), _connector='OR'), name='usuario_rol_superadmin_requiere_superuser'),
        ),
    ]
