# Generated by Django 6.0.4 on 2026-05-09 17:22

from django.db import migrations, models


def normalizar_staff_admin_django(apps, schema_editor):
    """Asegura que solo los superusuarios queden marcados como staff."""
    Usuario = apps.get_model('usuarios', 'Usuario')
    Usuario.objects.filter(is_superuser=True).update(is_staff=True)
    Usuario.objects.filter(is_superuser=False).update(is_staff=False)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0003_separar_superadministrador'),
    ]

    operations = [
        migrations.RunPython(
            normalizar_staff_admin_django,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(('is_staff', False), ('is_superuser', True), _connector='OR'), name='usuario_staff_requiere_superuser'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(('is_superuser', False), ('is_staff', True), _connector='OR'), name='usuario_superuser_requiere_staff'),
        ),
    ]
