# Generated by Django 6.0.4 on 2026-05-11 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_restringir_staff_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefono_movil',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Ingrese un teléfono móvil chileno con formato +56 seguido de 9 dígitos.', regex='^\\+56\\d{9}$')], verbose_name='Teléfono móvil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Ingrese un RUT válido.', regex='^[0-9kK.\\-\\s]+$')], verbose_name='RUT'),
        ),
    ]
