# Generated by Django 6.0.4 on 2026-05-13 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_permisos_y_grupos_operativos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('locacion', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('ACTIVA', 'Activa'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada'), ('HISTORICA', 'Historica')], default='PROGRAMADA', max_length=12)),
                ('es_proxima', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reuniones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reunion',
                'verbose_name_plural': 'reuniones',
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
    ]
