# Generated by Django 6.0.4 on 2026-05-13 19:30

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_reunion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reunion',
            options={
                'ordering': ['-fecha', '-hora', '-fecha_creacion'],
                'verbose_name': 'reunión',
                'verbose_name_plural': 'reuniones',
            },
        ),
        migrations.AddField(
            model_name='reunion',
            name='hora',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reunion',
            name='estado',
            field=models.CharField(
                choices=[
                    ('PROGRAMADA', 'Programada'),
                    ('ACTIVA', 'Activa'),
                    ('FINALIZADA', 'Finalizada'),
                    ('CANCELADA', 'Cancelada'),
                    ('HISTORICA', 'Histórica'),
                ],
                default='PROGRAMADA',
                max_length=12,
            ),
        ),
    ]
