# Generated by Django 6.0.4 on 2026-05-14 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_reunion_hora_estado_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='activada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reuniones_activadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reunion',
            name='fecha_activacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='reunion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVA')), fields=('estado',), name='solo_una_reunion_activa'),
        ),
    ]
