# Generated by Django 6.0.4 on 2026-05-14 21:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_reunion_activada_por_reunion_fecha_activacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaReunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente')], default='PRESENTE', max_length=10)),
                ('origen', models.CharField(choices=[('RUT', 'RUT'), ('QR', 'QR'), ('MANUAL', 'Manual'), ('AUTOMATICO', 'Automatico')], max_length=10)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('registrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL)),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='usuarios.reunion')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias_reunion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'asistencia de reunion',
                'verbose_name_plural': 'asistencias de reuniones',
                'ordering': ['-fecha_registro'],
                'constraints': [models.UniqueConstraint(fields=('reunion', 'socio'), name='asistencia_unica_por_socio_reunion')],
            },
        ),
    ]
