# Generated by Django 6.0.4 on 2026-05-18 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_asistenciareunion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reunion',
            name='finalizada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reuniones_finalizadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
