# Generated by Django 6.0.4 on 2026-05-19 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_reunion_fecha_finalizacion_reunion_finalizada_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='cancelada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reuniones_canceladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reunion',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reunion',
            name='motivo_cancelacion',
            field=models.TextField(blank=True),
        ),
    ]
