# Generated by Django 6.0.4 on 2026-05-19 19:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_reunion_cancelada_por_reunion_fecha_cancelacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesbloqueoSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha_desbloqueo', models.DateTimeField(default=django.utils.timezone.now)),
                ('inasistencias_al_desbloquear', models.PositiveIntegerField()),
                ('desbloqueado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desbloqueos_socios_realizados', to=settings.AUTH_USER_MODEL)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desbloqueos_asistencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'desbloqueo de socio',
                'verbose_name_plural': 'desbloqueos de socios',
                'ordering': ['-fecha_desbloqueo'],
            },
        ),
    ]
