# Generated by Django 6.0.4 on 2026-05-19 21:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_desbloqueosocio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desbloqueosocio',
            options={'ordering': ['-fecha_desbloqueo'], 'verbose_name': 'justificacion de inasistencia', 'verbose_name_plural': 'justificaciones de inasistencias'},
        ),
        migrations.AlterField(
            model_name='desbloqueosocio',
            name='desbloqueado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desbloqueos_socios_realizados', to=settings.AUTH_USER_MODEL, verbose_name='justificado por'),
        ),
        migrations.AlterField(
            model_name='desbloqueosocio',
            name='fecha_desbloqueo',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de justificacion'),
        ),
        migrations.AlterField(
            model_name='desbloqueosocio',
            name='inasistencias_al_desbloquear',
            field=models.PositiveIntegerField(verbose_name='inasistencias al justificar'),
        ),
        migrations.AlterField(
            model_name='desbloqueosocio',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desbloqueos_asistencia', to=settings.AUTH_USER_MODEL, verbose_name='socio'),
        ),
    ]
