# Generated by Django 6.0.4 on 2026-06-01 23:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_justificacion_asistencia_trazable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['last_name', 'apellido_materno', 'first_name', 'username'], 'permissions': (('gestionar_usuarios', 'Puede gestionar usuarios internos'), ('registrar_usuarios', 'Puede registrar usuarios internos'), ('registrar_socios', 'Puede registrar socios'), ('editar_socios', 'Puede editar socios'), ('acceder_asistencia', 'Puede acceder al modulo de asistencia'), ('eliminar_usuarios', 'Puede eliminar usuarios internos'), ('eliminar_socios', 'Puede eliminar socios'), ('administrar_privilegios', 'Puede administrar privilegios')), 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=150, verbose_name='Apellido materno'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_ingreso_proyecto',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de ingreso al proyecto'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Apellido paterno'),
        ),
    ]
