# Generated by Django 6.0.4 on 2026-06-02 00:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_alter_usuario_options_usuario_apellido_materno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionBloqueoSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_bloqueo', models.CharField(max_length=64, verbose_name='firma del bloqueo')),
                ('email_destino', models.EmailField(max_length=254, verbose_name='correo notificado')),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de notificacion')),
                ('total_inasistencias_efectivas', models.PositiveIntegerField(verbose_name='inasistencias efectivas notificadas')),
                ('enviada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones_bloqueo_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='enviada por')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones_bloqueo', to=settings.AUTH_USER_MODEL, verbose_name='socio')),
            ],
            options={
                'verbose_name': 'notificacion de bloqueo',
                'verbose_name_plural': 'notificaciones de bloqueo',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.AddConstraint(
            model_name='notificacionbloqueosocio',
            constraint=models.UniqueConstraint(fields=('socio', 'firma_bloqueo'), name='notificacion_bloqueo_unica_por_socio_firma'),
        ),
    ]
