# Generated by Django 6.0.4 on 2026-06-22 03:42

import django.core.validators
import usuarios.identificacion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_notificacionbloqueosocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Ingrese un RUT valido.', regex='^[0-9kK.\\-\\s]+$'), usuarios.identificacion.validar_rut_chileno], verbose_name='RUT'),
        ),
    ]
