# Generated by Django 6.0.4 on 2026-06-25 16:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def crear_cargas_historicas_previas(apps, schema_editor):
    Reunion = apps.get_model('usuarios', 'Reunion')
    AsistenciaReunion = apps.get_model('usuarios', 'AsistenciaReunion')
    CargaAsistenciaHistorica = apps.get_model('usuarios', 'CargaAsistenciaHistorica')

    reuniones_ids = list(
        AsistenciaReunion.objects.filter(
            reunion__estado='HISTORICA',
            origen='MANUAL',
            carga_historica__isnull=True,
        )
        .values_list('reunion_id', flat=True)
        .distinct()
    )

    for reunion_id in reuniones_ids:
        reunion = Reunion.objects.get(pk=reunion_id)
        asistencias = AsistenciaReunion.objects.filter(
            reunion_id=reunion_id,
            origen='MANUAL',
            carga_historica__isnull=True,
        ).order_by('fecha_registro')
        primera_asistencia = asistencias.first()
        if primera_asistencia is None:
            continue
        usuario_id = primera_asistencia.registrada_por_id or reunion.creador_id
        carga = CargaAsistenciaHistorica.objects.create(
            reunion_id=reunion_id,
            cargado_por_id=usuario_id,
            fecha_carga=primera_asistencia.fecha_registro,
            archivo_nombre='carga_historica_previa.csv',
            total_registros=asistencias.count(),
            total_presentes=asistencias.filter(estado='PRESENTE').count(),
            total_ausentes=asistencias.filter(estado='AUSENTE').count(),
        )
        asistencias.update(carga_historica_id=carga.pk)


def eliminar_cargas_historicas_previas(apps, schema_editor):
    AsistenciaReunion = apps.get_model('usuarios', 'AsistenciaReunion')
    CargaAsistenciaHistorica = apps.get_model('usuarios', 'CargaAsistenciaHistorica')

    cargas = CargaAsistenciaHistorica.objects.filter(
        archivo_nombre='carga_historica_previa.csv',
    )
    AsistenciaReunion.objects.filter(carga_historica__in=cargas).update(
        carga_historica=None,
    )
    cargas.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_alter_usuario_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaAsistenciaHistorica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateTimeField(default=django.utils.timezone.now)),
                ('archivo_nombre', models.CharField(blank=True, max_length=255)),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('total_presentes', models.PositiveIntegerField(default=0)),
                ('total_ausentes', models.PositiveIntegerField(default=0)),
                ('revertida', models.BooleanField(default=False)),
                ('fecha_reversion', models.DateTimeField(blank=True, null=True)),
                ('registros_revertidos', models.PositiveIntegerField(default=0)),
                ('cargado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas_asistencia_historica', to=settings.AUTH_USER_MODEL)),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_historicas', to='usuarios.reunion')),
                ('revertida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversiones_carga_asistencia_historica', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'carga historica de asistencia',
                'verbose_name_plural': 'cargas historicas de asistencia',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.AddField(
            model_name='asistenciareunion',
            name='carga_historica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias', to='usuarios.cargaasistenciahistorica'),
        ),
        migrations.RunPython(
            crear_cargas_historicas_previas,
            eliminar_cargas_historicas_previas,
        ),
    ]
