# Generated by Django 6.0.4 on 2026-06-29 16:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_cargaasistenciahistorica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AceptacionPrivacidadConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_politica', models.CharField(max_length=20)),
                ('texto_hash', models.CharField(max_length=64)),
                ('metodo_verificacion', models.CharField(choices=[('EMAIL_OTP', 'Codigo de un solo uso enviado por correo')], max_length=20)),
                ('fecha_aceptacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_hash', models.CharField(max_length=64)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aceptaciones_privacidad_consulta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'aceptacion de privacidad para consulta',
                'verbose_name_plural': 'aceptaciones de privacidad para consulta',
                'ordering': ['-fecha_aceptacion'],
                'constraints': [models.UniqueConstraint(fields=('socio', 'version_politica'), name='aceptacion_privacidad_unica_socio_version')],
            },
        ),
        migrations.CreateModel(
            name='SolicitudCodigoConsulta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_hash', models.CharField(max_length=64)),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('fecha_solicitud', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('fecha_expiracion', models.DateTimeField()),
                ('intentos_fallidos', models.PositiveSmallIntegerField(default=0)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('email_enviado', models.BooleanField(default=False)),
                ('socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_codigo_consulta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitud de codigo de consulta',
                'verbose_name_plural': 'solicitudes de codigo de consulta',
                'ordering': ['-fecha_solicitud'],
                'indexes': [models.Index(fields=['ip_hash', 'fecha_solicitud'], name='consulta_ip_fecha_idx'), models.Index(fields=['socio', 'fecha_solicitud'], name='consulta_socio_fecha_idx')],
            },
        ),
    ]
