# Generated by Django 6.0.4 on 2026-06-29 17:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_aceptacionprivacidadconsulta_solicitudcodigoconsulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LOGIN', 'Inicio de sesion'), ('RECUPERACION', 'Recuperacion de contrasena'), ('REAUTENTICACION', 'Reautenticacion sensible')], max_length=20)),
                ('identificador_hash', models.CharField(db_index=True, max_length=64)),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'intento de acceso',
                'verbose_name_plural': 'intentos de acceso',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['tipo', 'identificador_hash', 'fecha'], name='acceso_tipo_id_fecha_idx'), models.Index(fields=['tipo', 'ip_hash', 'fecha'], name='acceso_tipo_ip_fecha_idx')],
            },
        ),
    ]
