# Generated by Django 6.0.7 on 2026-09-27 23:15

import django.core.validators
import django.db.models.functions.text
import usuarios.identificacion
from django.db import migrations, models


def separar_identidades_y_normalizar_socios(apps, schema_editor):
    """Minimiza RUT internos y normaliza nombres/correos antes de restringir."""
    Usuario = apps.get_model('usuarios', 'Usuario')
    db_alias = schema_editor.connection.alias

    Usuario.objects.using(db_alias).exclude(rol='SOCIO').update(rut=None)
    socios = list(Usuario.objects.using(db_alias).filter(rol='SOCIO'))
    usuarios_actualizados = []
    for socio in socios:
        socio.first_name = (socio.first_name or '').strip().upper()
        socio.last_name = (socio.last_name or '').strip().upper()
        socio.apellido_materno = (socio.apellido_materno or '').strip().upper()
        socio.email = (socio.email or '').strip().lower()
        usuarios_actualizados.append(socio)
    if usuarios_actualizados:
        Usuario.objects.using(db_alias).bulk_update(
            usuarios_actualizados,
            ['first_name', 'last_name', 'apellido_materno', 'email'],
        )

    internos = list(Usuario.objects.using(db_alias).exclude(rol='SOCIO'))
    for usuario in internos:
        email_normalizado = (usuario.email or '').strip().lower()
        if email_normalizado != usuario.email:
            usuario.email = email_normalizado
            usuario.save(update_fields=['email'])


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0021_intentoacceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Ingrese un RUT valido.', regex='^[0-9kK.\\-\\s]+$'), usuarios.identificacion.validar_rut_chileno], verbose_name='RUT'),
        ),
        migrations.RunPython(
            separar_identidades_y_normalizar_socios,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='reunion',
            constraint=models.UniqueConstraint(fields=('fecha', 'hora'), name='reunion_unica_por_fecha_hora'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('rol', 'SOCIO')), name='usuario_email_unico_socios_ci'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('rol', 'SOCIO'), _negated=True), name='usuario_email_unico_internos_ci'),
        ),
    ]
