"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


try:
    from dotenv import load_dotenv
except ImportError:
    load_dotenv = None

if load_dotenv:
    load_dotenv(BASE_DIR / '.env')
else:
    env_path = BASE_DIR / '.env'
    if env_path.exists():
        for raw_line in env_path.read_text(encoding='utf-8').splitlines():
            line = raw_line.strip()
            if not line or line.startswith('#'):
                continue
            if line.startswith('export '):
                line = line[len('export '):].strip()
            if '=' not in line:
                continue

            key, value = line.split('=', 1)
            key = key.strip()
            value = value.strip()
            if not key or key in os.environ:
                continue
            if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
                value = value[1:-1]
            os.environ[key] = value


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def env_list(name, default=''):
    return [
        item.strip()
        for item in os.environ.get(name, default).split(',')
        if item.strip()
    ]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-dev-only-change-me',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)

if not DEBUG and SECRET_KEY == 'django-insecure-dev-only-change-me':
    raise RuntimeError('DJANGO_SECRET_KEY debe estar definido en produccion.')

ALLOWED_HOSTS = env_list(
    'DJANGO_ALLOWED_HOSTS',
    'localhost,127.0.0.1,testserver',
)

CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS')

# Seguridad HTTP. En desarrollo conserva HTTP local; en produccion falla cerrado.
SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', not DEBUG)
SESSION_COOKIE_SECURE = env_bool('DJANGO_SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = env_bool('DJANGO_CSRF_COOKIE_SECURE', not DEBUG)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
X_FRAME_OPTIONS = 'DENY'

# HSTS se habilita despues de comprobar certificado y redireccion HTTPS.
SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    'DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS',
    False,
)
SECURE_HSTS_PRELOAD = env_bool('DJANGO_SECURE_HSTS_PRELOAD', False)


# Application definition

INSTALLED_APPS = [
    'config.apps.SanRamonAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap5',
    'usuarios.apps.UsuariosConfig',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'

AUTH_USER_MODEL = 'usuarios.Usuario'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'usuarios.context_processors.permisos_navegacion',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [BASE_DIR / 'static']

STATIC_ROOT = BASE_DIR / 'staticfiles'

LOGIN_URL = 'usuarios:login'
LOGIN_REDIRECT_URL = 'usuarios:dashboard'
LOGOUT_REDIRECT_URL = 'usuarios:login'

EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', True)
EMAIL_USE_SSL = env_bool('EMAIL_USE_SSL', False)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL',
    EMAIL_HOST_USER or 'webmaster@localhost',
)
SERVER_EMAIL = os.environ.get('SERVER_EMAIL', DEFAULT_FROM_EMAIL)
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '20'))
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    (
        'django.core.mail.backends.smtp.EmailBackend'
        if EMAIL_HOST_USER
        else 'django.core.mail.backends.console.EmailBackend'
    ),
)

AUTHENTICATION_BACKENDS = [
    'usuarios.backends.EmailOrUsernameBackend',
]

AUDITORIA_LOG_PATH = BASE_DIR / 'auditoria.log'

# Consulta publica protegida por codigo de un solo uso.
CONSULTA_CODIGO_DURACION_MINUTOS = int(
    os.environ.get('CONSULTA_CODIGO_DURACION_MINUTOS', '10')
)
CONSULTA_CODIGO_MAX_INTENTOS = int(
    os.environ.get('CONSULTA_CODIGO_MAX_INTENTOS', '5')
)
CONSULTA_CODIGO_VENTANA_MINUTOS = int(
    os.environ.get('CONSULTA_CODIGO_VENTANA_MINUTOS', '2')
)
CONSULTA_CODIGO_MAX_SOLICITUDES_SOCIO = int(
    os.environ.get('CONSULTA_CODIGO_MAX_SOLICITUDES_SOCIO', '3')
)
CONSULTA_SESION_DURACION_MINUTOS = int(
    os.environ.get('CONSULTA_SESION_DURACION_MINUTOS', '15')
)
CONSULTA_CODIGO_RETENCION_DIAS = int(
    os.environ.get('CONSULTA_CODIGO_RETENCION_DIAS', '30')
)

# Seguridad de autenticacion y operaciones sensibles.
SEGURIDAD_LOGIN_VENTANA_MINUTOS = int(
    os.environ.get('SEGURIDAD_LOGIN_VENTANA_MINUTOS', '15')
)
SEGURIDAD_LOGIN_MAX_IDENTIFICADOR = int(
    os.environ.get('SEGURIDAD_LOGIN_MAX_IDENTIFICADOR', '5')
)
SEGURIDAD_LOGIN_MAX_IP = int(os.environ.get('SEGURIDAD_LOGIN_MAX_IP', '20'))
SEGURIDAD_RECUPERACION_VENTANA_MINUTOS = int(
    os.environ.get('SEGURIDAD_RECUPERACION_VENTANA_MINUTOS', '60')
)
SEGURIDAD_RECUPERACION_MAX_IDENTIFICADOR = int(
    os.environ.get('SEGURIDAD_RECUPERACION_MAX_IDENTIFICADOR', '3')
)
SEGURIDAD_RECUPERACION_MAX_IP = int(
    os.environ.get('SEGURIDAD_RECUPERACION_MAX_IP', '10')
)
SEGURIDAD_REAUTENTICACION_MINUTOS = int(
    os.environ.get('SEGURIDAD_REAUTENTICACION_MINUTOS', '10')
)
SEGURIDAD_INTENTOS_RETENCION_DIAS = int(
    os.environ.get('SEGURIDAD_INTENTOS_RETENCION_DIAS', '30')
)

# Claves separadas por coma. La primera cifra; las restantes permiten rotacion.
RESPALDO_ENCRYPTION_KEYS = env_list('RESPALDO_ENCRYPTION_KEYS')
AUDITORIA_HMAC_KEY = os.environ.get('AUDITORIA_HMAC_KEY', SECRET_KEY)
AUDITORIA_ROTACION_BYTES = int(
    os.environ.get('AUDITORIA_ROTACION_BYTES', str(10 * 1024 * 1024))
)
AUDITORIA_RETENCION_MESES = int(
    os.environ.get('AUDITORIA_RETENCION_MESES', '12')
)

# Las cargas CSV aceptadas permanecen en memoria y se rechazan sobre este limite.
CARGA_CSV_MAX_BYTES = int(
    os.environ.get('CARGA_CSV_MAX_BYTES', str(2 * 1024 * 1024))
)
FILE_UPLOAD_MAX_MEMORY_SIZE = CARGA_CSV_MAX_BYTES + (64 * 1024)

if not DEBUG and not RESPALDO_ENCRYPTION_KEYS:
    raise RuntimeError('RESPALDO_ENCRYPTION_KEYS debe estar definido en produccion.')
if not DEBUG and 'AUDITORIA_HMAC_KEY' not in os.environ:
    raise RuntimeError('AUDITORIA_HMAC_KEY debe estar definido en produccion.')
